   [tool.bumpversion]
   current_version = "0.1.9"
   commit = true
   tag = true
   tag_name = "v{new_version}"

   [tool.bumpversion.file_patterns]
   "natifylambda/__init__.py" = [
       {search = "__version__ = '{current_version}'", replace = "__version__ = '{new_version}'"},
   ]